### ISSUE TITLE
🔧 Photo Delivery System - Phase 1 Setup Guide (เริ่มต้นฟรี 100%)

### ISSUE THREAD

**Issue by Darksosix** [Darksosix/Photo-Delivery-System#1]
# 🚀 Photo Delivery System - Initial Setup Guide (Phase 1)

## 📋 ภาพรวมการ Setup
วันที่เริ่มโปรเจกต์: **6 มิถุนายน 2025**  
เป้าหมาย Phase 1: **Setup พื้นฐานและเตรียมเครื่องมือพัฒนา (2 สัปดาห์แรก)**

---

### 1.1 ติดตั้งซอฟต์แวร์พื้นฐาน
- [ ] **Node.js** (v18 หรือใหม่กว่า) - [ดาวน์โหลดที่นี่](https://nodejs.org/)
- [ ] **Git** - [ดาวน์โหลดที่นี่](https://git-scm.com/)
- [ ] **Visual Studio Code** พร้อม Extensions:
  - [ ] ES7+ React/Redux/React-Native snippets
  - [ ] Tailwind CSS IntelliSense
  - [ ] Prettier - Code formatter
  - [ ] Auto Rename Tag
  - [ ] GitLens

### 1.2 ตรวจสอบการติดตั้ง
```bash
# ตรวจสอบ Node.js version
node --version

# ตรวจสอบ npm version  
npm --version

# ตรวจสอบ Git version
git --version
```

---

### 2.1 โดเมน (ใช้ฟรีก่อน)
- [x] **ไม่จำเป็นต้องจดโดเมนตอนนี้**
- [ ] ใช้ Vercel subdomain ฟรี: `photo-delivery-system.vercel.app`
- [ ] เมื่อไหร่ที่พร้อม launch จริงค่อยจดโดเมนใหม่

### 2.2 สร้างบัญชี GitHub
- [ ] สร้าง GitHub Repository ใหม่
  ```
  Repository Name: photo-delivery-system
  Description: QR Code Photo Delivery Platform for Professional Photographers
  Visibility: Private (แนะนำในช่วงแรก)
  Initialize with README: ✅
  Add .gitignore: Node
  ```

### 2.3 สร้างบัญชี Vercel (Deployment - ฟรี)
- [ ] ไปที่ [vercel.com](https://vercel.com)
- [ ] Sign up ด้วย GitHub account
- [ ] Connect กับ Repository ที่สร้างไว้
- [ ] **Free Plan**: 100GB bandwidth/เดือน, Unlimited deployments

### 2.4 สร้างบัญชี Supabase (Database & Auth - ฟรี)
- [ ] ไปที่ [supabase.com](https://supabase.com)
- [ ] สร้าง Organization และ Project ใหม่
- [ ] เลือก Region: **Southeast Asia (Singapore)**
- [ ] **Free Plan**: 500MB database, 50MB file storage, 2GB bandwidth/เดือน
- [ ] บันทึก Database URL และ API Keys
  ```
  Project URL: https://xxxxx.supabase.co
  API Key (anon): eyJhbGciOiJIUzI1NiIsInR5cCI6...
  API Key (service_role): eyJhbGciOiJIUzI1NiIsInR5cCI6...
  Database Password: [สร้างรหัสผ่านที่แข็งแกร่ง]
  ```

### 2.5 สร้างบัญชี Cloudinary (Image Storage - ฟรี)
- [ ] ไปที่ [cloudinary.com](https://cloudinary.com)
- [ ] สร้างบัญชีฟรี: **25GB storage, 25GB bandwidth/เดือน**
- [ ] บันทึก Credentials
  ```
  Cloud Name: your-cloud-name
  API Key: 123456789012345
  API Secret: xxxxx-xxxxxxxxxx-xxxxxx
  ```

### 2.6 สร้างบัญชี Stripe (Payment - ฟรี Test Mode)
- [ ] ไปที่ [stripe.com](https://stripe.com)
- [ ] สร้างบัญชีประเทศไทย
- [ ] **ใช้เฉพาะ Test Mode ก่อน** (ไม่เสียค่าใช้จ่าย)
- [ ] บันทึก API Keys
  ```
  Publishable Key (Test): pk_test_xxxxx
  Secret Key (Test): sk_test_xxxxx
  Webhook Secret: whsec_xxxxx (จะได้ภายหลัง)
  ```

---

### 3.1 Clone Repository และ Setup
```bash
# Clone repository
git clone https://github.com/Darksosix/photo-delivery-system.git
cd photo-delivery-system

# สร้าง Next.js project ใหม่
npx create-next-app@latest . --typescript --tailwind --eslint --app --src-dir --import-alias "@/*"

# ติดตั้ง packages เพิ่มเติม
npm install @supabase/supabase-js @supabase/ssr prisma @prisma/client
npm install cloudinary next-cloudinary
npm install stripe
npm install qrcode @types/qrcode
npm install lucide-react class-variance-authority clsx tailwind-merge
npm install @radix-ui/react-dialog @radix-ui/react-dropdown-menu @radix-ui/react-select
npm install react-hook-form @hookform/resolvers zod
npm install next-themes

# Dev dependencies
npm install -D @types/node prisma tailwindcss-animate
```

### 3.2 สร้างโครงสร้างโฟลเดอร์
```bash
# สร้างโครงสร้างโฟลเดอร์
mkdir -p src/app/\(auth\)/login src/app/\(auth\)/register
mkdir -p src/app/\(dashboard\)/events src/app/\(dashboard\)/photos src/app/\(dashboard\)/settings
mkdir -p src/app/gallery/\[eventId\]
mkdir -p src/app/api/auth src/app/api/events src/app/api/photos src/app/api/payments
mkdir -p src/components/ui src/components/auth src/components/event src/components/photo src/components/payment
mkdir -p src/lib/supabase src/lib/cloudinary src/lib/stripe src/lib/utils
mkdir -p src/types
```

```
src/
├── app/
│   ├── (auth)/
│   │   ├── login/
│   │   └── register/
│   ├── (dashboard)/
│   │   ├── events/
│   │   ├── photos/
│   │   └── settings/
│   ├── gallery/
│   │   └── [eventId]/
│   ├── api/
│   │   ├── auth/
│   │   ├── events/
│   │   ├── photos/
│   │   └── payments/
│   └── globals.css
├── components/
│   ├── ui/
│   ├── auth/
│   ├── event/
│   ├── photo/
│   └── payment/
├── lib/
│   ├── supabase/
│   ├── cloudinary/
│   ├── stripe/
│   └── utils/
└── types/
    └── index.ts
```

### 3.3 สร้างไฟล์ Environment Variables
```bash
# สร้างไฟล์ .env.local
touch .env.local
```

```env
# .env.local
# Supabase
NEXT_PUBLIC_SUPABASE_URL=https://xxxxx.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6...
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6...

# Cloudinary
NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=your-cloud-name
CLOUDINARY_API_KEY=123456789012345
CLOUDINARY_API_SECRET=xxxxx-xxxxxxxxxx-xxxxxx

# Stripe
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_xxxxx
STRIPE_SECRET_KEY=sk_test_xxxxx
STRIPE_WEBHOOK_SECRET=whsec_xxxxx

# App
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=your-super-secret-jwt-secret-here

# Database
DATABASE_URL="postgresql://postgres:[password]@db.xxxxx.supabase.co:5432/postgres"
```

---

### 4.1 สร้าง Prisma Schema
```bash
# Initialize Prisma
npx prisma init
```

```prisma
// prisma/schema.prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        String   @id @default(cuid())
  email     String   @unique
  name      String?
  avatar    String?
  plan      Plan     @default(FREE)
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  
  events    Event[]
  downloads Download[]
  
  @@map("users")
}

model Event {
  id          String   @id @default(cuid())
  name        String
  description String?
  eventDate   DateTime
  qrCode      String   @unique
  isActive    Boolean  @default(true)
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
  
  userId      String
  user        User     @relation(fields: [userId], references: [id], onDelete: Cascade)
  
  photos      Photo[]
  downloads   Download[]
  
  @@map("events")
}

model Photo {
  id           String   @id @default(cuid())
  fileName     String
  originalName String
  cloudinaryId String
  publicUrl    String
  thumbnailUrl String
  fileSize     Int
  width        Int
  height       Int
  uploadedAt   DateTime @default(now())
  
  eventId      String
  event        Event    @relation(fields: [eventId], references: [id], onDelete: Cascade)
  
  downloads    PhotoDownload[]
  
  @@map("photos")
}

model Download {
  id          String   @id @default(cuid())
  type        DownloadType
  totalPrice  Float
  status      DownloadStatus @default(PENDING)
  createdAt   DateTime @default(now())
  completedAt DateTime?
  
  userId      String?
  user        User?    @relation(fields: [userId], references: [id])
  eventId     String
  event       Event    @relation(fields: [eventId], references: [id])
  
  photos      PhotoDownload[]
  
  @@map("downloads")
}

model PhotoDownload {
  id         String @id @default(cuid())
  price      Float
  
  photoId    String
  photo      Photo  @relation(fields: [photoId], references: [id])
  downloadId String
  download   Download @relation(fields: [downloadId], references: [id])
  
  @@map("photo_downloads")
}

enum Plan {
  FREE
  PRO
  STUDIO
}

enum DownloadType {
  SINGLE
  BUNDLE
}

enum DownloadStatus {
  PENDING
  PROCESSING
  COMPLETED
  FAILED
}
```

### 4.2 Run Database Migration
```bash
# Generate Prisma Client
npx prisma generate

# Push schema to database
npx prisma db push

# Open Prisma Studio (optional)
npx prisma studio
```

---

### 5.1 สร้าง Tailwind Config
```typescript
// tailwind.config.ts
import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: ["class"],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
export default config
```

### 5.2 สร้าง Global CSS Variables
```css
/* src/app/globals.css */
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 84% 4.9%;
    --card: 0 0% 100%;
    --card-foreground: 222.2 84% 4.9%;
    --popover: 0 0% 100%;
    --popover-foreground: 222.2 84% 4.9%;
    --primary: 221.2 83.2% 53.3%;
    --primary-foreground: 210 40% 98%;
    --secondary: 210 40% 96%;
    --secondary-foreground: 222.2 84% 4.9%;
    --muted: 210 40% 96%;
    --muted-foreground: 215.4 16.3% 46.9%;
    --accent: 210 40% 96%;
    --accent-foreground: 222.2 84% 4.9%;
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 210 40% 98%;
    --border: 214.3 31.8% 91.4%;
    --input: 214.3 31.8% 91.4%;
    --ring: 221.2 83.2% 53.3%;
    --radius: 0.5rem;
  }

  .dark {
    --background: 222.2 84% 4.9%;
    --foreground: 210 40% 98%;
    --card: 222.2 84% 4.9%;
    --card-foreground: 210 40% 98%;
    --popover: 222.2 84% 4.9%;
    --popover-foreground: 210 40% 98%;
    --primary: 217.2 91.2% 59.8%;
    --primary-foreground: 222.2 84% 4.9%;
    --secondary: 217.2 32.6% 17.5%;
    --secondary-foreground: 210 40% 98%;
    --muted: 217.2 32.6% 17.5%;
    --muted-foreground: 215 20.2% 65.1%;
    --accent: 217.2 32.6% 17.5%;
    --accent-foreground: 210 40% 98%;
    --destructive: 0 62.8% 30.6%;
    --destructive-foreground: 210 40% 98%;
    --border: 217.2 32.6% 17.5%;
    --input: 217.2 32.6% 17.5%;
    --ring: 224.3 76.3% 94.1%;
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}
```

---

### 6.1 สร้างหน้า Home Page ทดสอบ
```typescript
// src/app/page.tsx
export default function Home() {
  return (
    <main className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-50 to-indigo-100">
      <div className="text-center">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">
          🎯 Photo Delivery System
        </h1>
        <p className="text-xl text-gray-600 mb-8">
          สแกนครั้งเดียว รับภาพทันที
        </p>
        <div className="space-y-2 text-sm text-gray-500">
          <p>✅ Next.js Setup สำเร็จ</p>
          <p>✅ Tailwind CSS ทำงาน</p>
          <p>✅ TypeScript พร้อมใช้งาน</p>
          <p>✅ ใช้ฟรี Tier ทุกบริการ</p>
        </div>
      </div>
    </main>
  )
}
```

### 6.2 ทดสอบ Development Server
```bash
# รัน development server
npm run dev

# เปิด browser ไปที่ http://localhost:3000
```

### 6.3 Deploy ทดสอบบน Vercel
```bash
# Push code ไป GitHub
git add .
git commit -m "Initial project setup"
git push origin main

# Vercel จะ auto-deploy เมื่อ push ไป main branch
# URL จะเป็น: https://photo-delivery-system.vercel.app
```

---

### การเตรียมสภาพแวดล้อม
- [ ] ติดตั้ง Node.js, Git, VS Code พร้อม Extensions
- [ ] ตรวจสอบการติดตั้งทั้งหมดเรียบร้อย

### การลงทะเบียนบริการ (ใช้ฟรี Plan ทั้งหมด)
- [ ] **ยังไม่จดโดเมน** - ใช้ Vercel subdomain
- [ ] สร้าง GitHub Repository
- [ ] Setup Vercel Project (Free Plan)
- [ ] สร้าง Supabase Project + Database (Free: 500MB)
- [ ] สร้าง Cloudinary Account (Free: 25GB)
- [ ] สร้าง Stripe Account (Test Mode - ฟรี)

### การ Setup โปรเจกต์
- [ ] สร้าง Next.js Project พร้อม TypeScript + Tailwind
- [ ] ติดตั้ง Dependencies ทั้งหมด
- [ ] สร้างโครงสร้างโฟลเดอร์
- [ ] ตั้งค่า Environment Variables
- [ ] Setup Prisma + Database Schema
- [ ] สร้าง UI Components พื้นฐาน

### การทดสอบ
- [ ] ทดสอบ Local Development Server
- [ ] ทดสอบ Database Connection
- [ ] Deploy ทดสอบบน Vercel
- [ ] ตรวจสอบ Environment Variables บน Production

---

## 💰 ค่าใช้จ่าย Phase 1 (ใช้ฟรีทั้งหมด!)

| บริการ | Plan | ข้อจำกัด | ค่าใช้จ่าย |
|---------|------|----------|----------|
| **GitHub** | Free | Private repos, unlimited public | ฟรี |
| **Vercel** | Hobby | 100GB bandwidth/เดือน | ฟรี |
| **Supabase** | Free | 500MB database, 2GB bandwidth | ฟรี |
| **Cloudinary** | Free | 25GB storage + bandwidth | ฟรี |
| **Stripe** | Test Mode | ทดสอบได้ไม่จำกัด | ฟรี |
| **โดเมน** | ยังไม่ใช้ | ใช้ .vercel.app | ฟรี |
| **รวม** | | | **฿0** |

---

## 🎯 เป้าหมาย Week 2

หลังจากจบ Week 1 แล้ว Week 2 จะเริ่ม:
1. **Authentication System**: Setup Supabase Auth + Protected Routes
2. **Basic UI Components**: สร้าง Dashboard Layout
3. **Event Management**: หน้าสร้างและจัดการ Event
4. **Photo Upload**: ระบบอัปโหลดรูปภาพพื้นฐาน

---

## 🚀 การ Upgrade เมื่อพร้อม

เมื่อโปรเจกต์เริ่มมีลูกค้าจริงแล้ว สามารถ upgrade ได้:

### เมื่อมีลูกค้า 10+ คน
- [ ] จดโดเมนที่ต้องการ (฿300-800/ปี)
- [ ] Supabase Pro: $25/เดือน (2GB database, 100GB bandwidth)
- [ ] Cloudinary Advanced: $99/เดือน (100GB, advanced features)

### เมื่อเริ่มทำรายได้
- [ ] Stripe Live Mode (2.9% + ฿10 per transaction)
- [ ] Professional domain email
- [ ] Backup และ monitoring services

---

### ปัญหา Node.js Version
```bash
# ถ้า Node.js version เก่าเกินไป
nvm install 18
nvm use 18
```

### ปัญหา Database Connection
```bash
# ตรวจสอบ Database URL ใน .env.local
# ลอง connect ผ่าน Prisma Studio
npx prisma studio
```

### ปัญหา Vercel Deployment
- ตรวจสอบ Environment Variables ใน Vercel Dashboard
- ตรวจสอบ Build Logs หา Error

### เกินขิดจำกัด Free Plan
- **Supabase**: ใช้ข้อมูลไม่เกิน 500MB ในช่วงทดสอบ
- **Cloudinary**: อัปโหลดรูปขนาดเล็กในช่วง dev
- **Vercel**: 100GB bandwidth เพียงพอสำหรับ beta testing

---

**📞 ต้องการความช่วยเหลือ?**
สร้าง GitHub Issue ใหม่ด้วย label `help-needed` และอธิบายปัญหาที่พบ

---

*🚀 "เริ่มต้นฟรี... พัฒนาอย่างยั่งยืน!"*
